# Generated by Django 5.0 on 2024-10-26 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0002_alter_plan_tenders_report_tender_tender_republished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='republished_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workon', to='monitoring_app.tender_republished'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='proc_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workon', to='monitoring_app.tender'),
        ),
    ]
