# Generated by Django 5.0 on 2024-10-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0003_procedure_republished_item_alter_procedure_proc_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='overall_department',
            name='republished',
            field=models.ManyToManyField(related_name='all_republished', to='monitoring_app.tender'),
        ),
        migrations.AddField(
            model_name='overall_stages',
            name='republished_on_stage',
            field=models.ManyToManyField(related_name='tenders_on_stage', to='monitoring_app.tender_republished'),
        ),
    ]
