# Generated by Django 5.0 on 2024-10-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0005_plan_tenders_report_removed_tender_removed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overall_department',
            name='rep_committed',
            field=models.ManyToManyField(related_name='department_tenders_committed', to='monitoring_app.tender_republished'),
        ),
    ]
