# Generated by Django 5.0 on 2024-10-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0006_overall_department_rep_committed'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_tenders_report',
            name='actual_contract_management_end_date',
            field=models.DateField(null=True),
        ),
    ]
